# Cloud-System Module Sync-Proxy

proxy:
  motd: '§b§lCloud§3§lSystem §7- §f§lv1.0.1\n§fSyncProxy §7module!'
  version:
    name: '§cMaintenance'
    id: 0
  description:
    - 'Join my'
    - 'network!'

tabList:
  update: 20
  header: ' §b§lCloud§3§lSystem §7- §f§lv1.0.1 \n §fSyncProxy §7module! \n'
  footer: '\n §7Date: §f%date% \n §7Time: §f%time% '