# Cloud-System Module Sync-Proxy

# Placeholders:
#
serverList:
  motd: '§b§lCloud§3§lSystem §8- §7§lDynamic §f§oserver §7handling\n§8» §aOnline§7: §eBungee-1'
  version:
    name: '§8» §cMaintenance'
    id: 0
  description:
    - 'Join my'
    - 'network!'

tabList:
  update: 20
  header: ' §b§lCloud§3§lSystem §8- \n'
  footer: '\n §7Date: §f%date% \n §7Time: §f%time% '